FROM openjdk:11.0.13-slim-bullseye

ARG VERSION
ARG ARCH
ARG PYTHON_CONFLUENT_DOCKER_UTILS_INSTALL_SPEC="git+https://github.com/confluentinc/confluent-docker-utils@v0.0.49"

LABEL maintainer="jackcviers@gmail.com"
LABEL version=$VERSION
LABEL name="cp-base"
LABEL summary="Common base image for Confluent Components' Docker images."

ENV LANG="C.UTF-8"
ENV CUB_CLASSPATH='"/usr/share/java/cp-base-new/*"'
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update \
	&& apt install -y \
	wget \
	nmap \
	ncat \
	python3 \
	procps \
	krb5-user \
	iputils-tracepath \
	iputils-ping \
	iputils-clockdiff \
	iputils-arping \
	python3-pip \	
	git \
	&& update-alternatives --install /usr/bin/python python /usr/bin/python3 99 \
	&& python3 -m pip install --upgrade "pip>=21,<22" \
	&& python3 -m pip install --prefer-binary --prefix=/usr/local --upgrade ${PYTHON_CONFLUENT_DOCKER_UTILS_INSTALL_SPEC} \
	&& apt remove -y git \
	&& apt clean \
	&& rm -rf /tmp/* \
	&& mkdir -p /etc/confluent/docker /usr/logs/ \
	&& useradd --no-log-init --create-home --shell /bin/bash appuser \
	&& chown appuser:appuser -R /etc/confluent/

ADD --chown=appuser:appuser https://repo1.maven.org/maven2/net/sourceforge/argparse4j/argparse4j/0.7.0/argparse4j-0.7.0.jar /usr/share/java/cp-base-new/

ADD --chown=appuser:appuser https://repo1.maven.org/maven2/org/apache/yetus/audience-annotations/0.5.0/audience-annotations-0.5.0.jar /usr/share/java/cp-base-new/

ADD --chown=appuser:appuser https://packages.confluent.io/maven/io/confluent/common-utils/7.0.0/common-utils-7.0.0.jar /usr/share/java/cp-base-new/

ADD --chown=appuser:appuser https://repo1.maven.org/maven2/commons-cli/commons-cli/1.4/commons-cli-1.4.jar /usr/share/java/cp-base-new/

ADD --chown=appuser:appuser https://repo1.maven.org/maven2/io/confluent/confluent-log4j/1.2.17-cp2/confluent-log4j-1.2.17-cp2.jar /usr/share/java/cp-base-new/

ADD --chown=appuser:appuser https://packages.confluent.io/maven/io/confluent/disk-usage-agent/7.0.0/disk-usage-agent-7.0.0.jar /usr/share/java/cp-base-new/

ADD --chown=appuser:appuser https://repo1.maven.org/maven2/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar /usr/share/java/cp-base-new/

ADD --chown=appuser:appuser https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.3/jackson-annotations-2.12.3.jar /usr/share/java/cp-base-new/

ADD --chown=appuser:appuser https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.12.3/jackson-core-2.12.3.jar /usr/share/java/cp-base-new/

ADD --chown=appuser:appuser https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.12.3/jackson-databind-2.12.3.jar /usr/share/java/cp-base-new/

ADD --chown=appuser:appuser https://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-csv/2.12.3/jackson-dataformat-csv-2.12.3.jar /usr/share/java/cp-base-new/

ADD --chown=appuser:appuser https://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.12.3/jackson-dataformat-yaml-2.12.3.jar /usr/share/java/cp-base-new/

ADD --chown=appuser:appuser https://repo1.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.12.3/jackson-datatype-jdk8-2.12.3.jar /usr/share/java/cp-base-new/

ADD --chown=appuser:appuser https://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-scala_2.13/2.12.3/jackson-module-scala_2.13-2.12.3.jar /usr/share/java/cp-base-new/

ADD --chown=appuser:appuser https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.14.0/jmx_prometheus_javaagent-0.14.0.jar /usr/share/java/cp-base-new/

ADD --chown=appuser:appuser https://repo1.maven.org/maven2/org/jolokia/jolokia-core/1.6.2/jolokia-core-1.6.2.jar /usr/share/java/cp-base-new/

ADD --chown=appuser:appuser https://repo1.maven.org/maven2/org/jolokia/jolokia-jvm/1.6.2/jolokia-jvm-1.6.2-agent.jar /usr/share/java/cp-base-new/

ADD --chown=appuser:appuser https://repo1.maven.org/maven2/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar /usr/share/java/cp-base-new/

ADD --chown=appuser:appuser https://repo1.maven.org/maven2/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar /usr/share/java/cp-base-new/

ADD --chown=appuser:appuser https://packages.confluent.io/maven/org/apache/kafka/kafka-clients/7.0.0-ccs/kafka-clients-7.0.0-ccs.jar /usr/share/java/cp-base-new/

ADD --chown=appuser:appuser https://packages.confluent.io/maven/org/apache/kafka/kafka-metadata/7.0.0-ccs/kafka-metadata-7.0.0-ccs.jar /usr/share/java/cp-base-new/

ADD --chown=appuser:appuser https://packages.confluent.io/maven/org/apache/kafka/kafka-raft/7.0.0-ccs/kafka-raft-7.0.0-ccs.jar /usr/share/java/cp-base-new/

ADD --chown=appuser:appuser https://packages.confluent.io/maven/org/apache/kafka/kafka-server-common/7.0.0-ccs/kafka-server-common-7.0.0-ccs.jar /usr/share/java/cp-base-new/

ADD --chown=appuser:appuser https://packages.confluent.io/maven/org/apache/kafka/kafka-storage/7.0.0-ccs/kafka-storage-7.0.0-ccs.jar /usr/share/java/cp-base-new/

ADD --chown=appuser:appuser https://packages.confluent.io/maven/org/apache/kafka/kafka-storage-api/7.0.0-ccs/kafka-storage-api-7.0.0-ccs.jar /usr/share/java/cp-base-new/

ADD --chown=appuser:appuser https://packages.confluent.io/maven/org/apache/kafka/kafka_2.13/7.0.0-ccs/kafka_2.13-7.0.0-ccs.jar /usr/share/java/cp-base-new/

ADD --chown=appuser:appuser https://repo1.maven.org/maven2/org/lz4/lz4-java/1.7.1/lz4-java-1.7.1.jar /usr/share/java/cp-base-new/

ADD --chown=appuser:appuser https://repo1.maven.org/maven2/com/yammer/metrics/metrics-core/2.2.0/metrics-core-2.2.0.jar /usr/share/java/cp-base-new/

ADD --chown=appuser:appuser https://repo1.maven.org/maven2/io/dropwizard/metrics/metrics-core/4.1.12.1/metrics-core-4.1.12.1.jar /usr/share/java/cp-base-new/

ADD --chown=appuser:appuser https://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.8/paranamer-2.8.jar /usr/share/java/cp-base-new/

CMD ["echo" "built!"]
