# Copyright 2021 Jack Viers

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY_USER: ${{ secrets.DOCKER_HUB_JACKCVIERS_USERNAME }}
  IMAGE_REGISTRY: docker.io
  REGISTRY_PASSWORD: ${{ secrets.DOCKER_HUB_JACKCVIERS_ACCESS_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout project (pull-request)
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v2.3.2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Checkout project (main)
        if: github.event_name == 'push'
        uses: actions/checkout@v2
      - name: Install nerdctl-full
        run: |
          sudo apt -qq update
          sudo apt -qq install -y wget qemu-user-static gpg
          wget -q https://github.com/containerd/nerdctl/releases/download/v0.16.1/nerdctl-full-0.16.1-linux-amd64.tar.gz
          sudo tar Cxzf /usr/local nerdctl-full-0.16.1-linux-amd64.tar.gz
          loginctl enable-linger runner
          sleep 1
          ls /run/user/$UID
          KDG_RUNTIME_DIR=/run/user/$UID systemctl enable --now containerd
      - name: Install expect
        run: |
          sudo apt update
          sudo apt install -y expect
      - name: Setup build-essentials
        run: |
          sudo apt update
          sudo apt install -y build-essential
      - name: Setup build and test for ubuntu
        run: |
          echo "BATS_INSTALL_SCRIPT_LOCATION=./devel/src/main/bash/com/github/jackcviers/confluent/cp/images/installation/scripts/install_bats_ubuntu.sh" >> .local.make
          echo "BATS_LIBS_INSTALL_LOCATION=/usr/local/lib" >> .local.make
          echo "IMAGES_BUILD_TOOL=nerdctl" >> .local.make
      - name: Setup Bats
        run: |
          make install-bats
      - name: Run Build & Tests
        if: github.event_name == 'pull_request'
        run: |
          sudo nerdctl build --platform=amd64,arm64 --progress=tty -t localhost:5000/***/cp-base-new:7.0.0 --build-arg ARCH="" --build-arg VERSION=7.0.0 --build-arg UPSTREAM_REPOSITORY=localhost:5000 -f ./devel/src/main/docker/cp-base-new/Dockerfile ./devel/src/main/docker/cp-base-new
          # sudo make devel
      - name: Log in to Docker.io
        if: github.event_name == 'push'
        run: |
          sudo nerdctl login -p ${{ secrets.DOCKER_HUB_JACKCVIERS_ACCESS_TOKEN }} -u ${{ secrets.DOCKER_HUB_JACKCVIERS_USERNAME }} docker.io
      - name: Run Build & Tests & Publish to DOCKER.IO
        if: github.event_name == 'push'
        run: |
          sudo make ci
